# Filename: .github/workflows/android_build.yml

# Workflow name
name: Build Android APK

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ] # Adjust if your default branch is different (e.g., master)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds the Android APK
  build-android:
    # Use the standard latest stable Ubuntu runner
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checkout code using current major version
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 17 using current major version
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Set up Flutter SDK using the standard official stable tag (v1)
      #    Pin the exact Flutter version your project requires.
      - name: Set up Flutter SDK
        uses: actions/setup-flutter@v1 # Standard stable tag
        with:
          flutter-version: '3.7.3' # Your specific Flutter version
          cache: true # Recommended for performance

      # 4. Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # --- Optional Steps (Uncomment to enable) ---
      # # 5. Check Formatting
      # - name: Check Formatting
      #   run: flutter format --set-exit-if-changed .
      # # 6. Run Analyzer
      # - name: Run Analyzer
      #   run: flutter analyze
      # # 7. Run Tests
      # - name: Run Tests
      #   run: flutter test
      # --- End Optional Steps ---

      # 8. Build the Android APK in release mode (unsigned)
      - name: Build APK
        run: flutter build apk --release

      # 9. Upload the generated APK artifact using current major version
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error # Fail if APK is missing

      # --- Optional: Build App Bundle (AAB) instead ---
      # ... (AAB steps remain the same) ...
